service: counting-paths-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 150
  profile: serverless-framework

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /api/count-paths
          cors: true
      - http:
          method: ANY
          path: /api/count-paths/{any+}
          cors: true

plugins:
  - serverless-offline

custom:
  dotenv:
    basePath: ./
